import type { NextPage } from "next";

import Head from "next/head";
import PrincipalNavBar from "../components/PrincipalNavBar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Welcome|awos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <PrincipalNavBar />
      </header>

    </div>
  );
};

export default Home;
